[project]
name = "ai-agents-in-action"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "py-trees>=2.2.3",
    "requests>=2.28.0",
    "openai>=1.0.0",
]
